3.0 holding master
singpath/classmentors pull request #109
Opened 2016-09-18 16:42 UTC by shiquan-lim

Implemented Cohort filtered ranking and sorted out most conflicts between the 3.0 update and the team's code.

Team activities are not included in this update

2016-09-18 22:42 UTC, dinoboff commented on src/classmentors/components/cohorts/cohorts.js
> +                                    loadUserAchievements();
Any reason why you use recursive calls instead of Array methods or simple loops?

2016-09-18 22:52 UTC, dinoboff commented on src/classmentors/components/events/events.js
> +            var editor = ace.edit(document.querySelector('#editor'));
Is it possible to use the inject to find the element instead global, which will prevent you to test it.

Also, it's not important for this PR but you should avoid manipulate the DOM from a controller. You should either create a component / directive to handle this, or reuse [spfEditor](https://github.com/singpath/classmentors/blob/master/src/packages/singpath-core/src/components/ace/ace.js) component.

2016-09-18 22:56 UTC, dinoboff commented on src/classmentors/components/cohorts/cohorts.js
> +        console.log(self.mappedEvents);
Please use $log if it's meant to be permanent. Try to avoid committing console calls

2016-09-18 22:59 UTC, dinoboff reviewed
Sorry for if using `$document` instead document broke the editor. Is there an alternative to use `document` directly?

2016-09-18 23:08 UTC, dinoboff commented on src/classmentors/components/events/events.js
> +            var editor = ace.edit(document.querySelector('#editor'));
Can you please try with: `$document[0].querySelector('#editor');` or `$document[0].getElementById('editor');`.

2016-09-19 00:34 UTC, shiquan-lim commented on src/classmentors/components/cohorts/cohorts.js
> +                                    loadUserAchievements();
No particular reason, I just wanted to ensure that the program does not attempt to make another call to the firebase until the previous promise had been resolved and the data handled. This seemed like the easiest way to do so. If there are performance of reliability related reasons NOT to use this method, then I can also change it.

2016-09-19 00:35 UTC, shiquan-lim commented on src/classmentors/components/cohorts/cohorts.js
> +        console.log(self.mappedEvents);
Yes, this is not meant to be permanent. Apologies. We will exclude console calls in future PRs

2016-09-19 00:36 UTC, shiquan-lim commented on src/classmentors/components/events/events.js
> +            var editor = ace.edit(document.querySelector('#editor'));
Will attempt to do so. Out of curiosity, is there a reason why you recommend this?
"_you should avoid manipulate the DOM from a controller_"

2016-09-19 01:04 UTC, dinoboff commented on src/classmentors/components/cohorts/cohorts.js
> +                                    loadUserAchievements();
It's not obviously what the function is meant to do. You might only notice at the end it's an iteration and personalty I didn't notice it was meant to be sequential. A `for` loop, `forEach` or `reduce` AFAIK is more idiomatic in this case.

Is there a noticeable performance issue when doing it in parallel?

2016-09-19 01:18 UTC, dinoboff commented on src/classmentors/components/events/events.js
> +            var editor = ace.edit(document.querySelector('#editor'));
Separation of concern. The controller extends the scope by providing some values and event handlers. The controller doesn't need to a value comes from a textarea and ace editor.

And It easier to set a textarea as an editor in your template by adding a directive (the one we are using for singpath or something like [UI-Ace](https://github.com/angular-ui/ui-ace)) than to create that textearea in your template and then transform some arbitrary element from your controller.

2016-09-20 00:06 UTC, dinoboff commented on src/classmentors/components/challenges/teamActivity/team-view-create.html
> +              <md-option ng-$at="team in ctrl.teams" ng-value="team.name"></md-option>
What is "ng-$att"

2016-09-20 00:14 UTC, dinoboff commented on src/classmentors/services.js
> +                }
Unnecessary.

2016-09-20 00:16 UTC, dinoboff commented on src/classmentors/services.js
> +        },
You can use `./node_modules/.bin/eslint src/classmentors/services.js --fix` to reformat this file.

2016-09-20 00:22 UTC, dinoboff requested changes
There are still a few the `spfFirebase` to remove.

The indent changes in services.js should be reverted.

2016-09-20 00:55 UTC, dinoboff commented on src/classmentors/components/challenges/challenges.js
> +              spfFirebase.set(['classMentors/eventTeams', event.$id],taskId)
Here, you trying to set `classMentors/eventTeams/$eventId` to a literal value...

2016-09-20 00:56 UTC, dinoboff commented on src/classmentors/components/challenges/challenges.js
> +                    spfFirebase.push(['classMentors/eventTeams/', event.$id,taskId],team)
...And then here you're trying to push an object to classMentors/eventTeams/$eventId/$taskId.

I am guessing there's a typo.

2016-09-20 10:02 UTC, shiquan-lim commented on src/classmentors/components/challenges/challenges.js
> +                    spfFirebase.push(['classMentors/eventTeams/', event.$id,taskId],team)
Yes challenges are being fixed now. These are for the team activities function, coming in the next PR.

2016-09-20 10:02 UTC, shiquan-lim commented on src/classmentors/components/challenges/challenges.js
> +              spfFirebase.set(['classMentors/eventTeams', event.$id],taskId)
This will also be fixed in the next PR

2016-09-20 10:02 UTC, shiquan-lim commented on src/classmentors/services.js
> +        },
Will do.

2016-09-20 10:03 UTC, shiquan-lim commented on src/classmentors/services.js
> +                }
This wasnt implemented by us, I believe. But we can remove it

2016-09-21 06:25 UTC, shiquan-lim commented on src/classmentors/components/events/events.js
> +            var editor = ace.edit(document.querySelector('#editor'));
`$document[0].querySelector('#editor');` works

2016-09-21 07:01 UTC, merged

2016-09-21 07:25 UTC, shiquan-lim commented on src/classmentors/services.js
> +        },
`./node_modules/.bin/eslint src/classmentors/services.js --fix` still leaves some indentation errors. Most have been fixed though.

2016-09-21 08:55 UTC, dinoboff commented on src/classmentors/services.js
> +                }
sorry I meant the indentation change